#!/bin/bash
set -e
echoerr() {
	echo 1>&2 "$@"
}
run() {
	file="$1"
	shift
	name=`basename "$file"`
	echoerr "Running $name..."
	./plx -o "$name.s" "$@" "$file"
	nasm -felf32 "$name.s"
	gcc -m32 "$name.o"
	if [ -f "$file.in" ]; then
		./a.out < "$file.in"
	else
		./a.out
	fi
}
if [ "x$1" = x-a ]; then
	shift
	# run all tests for which a reference output file is given
	for out in tests/*.out; do
		run > out "${out%.out}" "$@"
		cmp out "$out"
	done
else
	run "tests/$1"
fi
