#!/usr/bin/perl

use integer;

open OUT, '>', 'preamble.inc';

sub process {
	my $name = shift;
	open IN, '<', $name;
	print OUT "const char $name\[] =\n";
	%s = ("\t" => '\t', '"' => '\"', '\\' => '\\\\');
	while (<IN>) {
		chomp;
		s/([\\\t"])/$s{$1}/ge;
		print OUT "\"$_\\n\"\n";
	}
	print OUT ";\n";
	close IN;
}

process('preamble1');
process('preamble2');
