#!/usr/bin/perl

use integer;

open IN, '< preamble';
open OUT, '> preamble.inc';
print OUT "const char preamble[] =\n";
%s = ("\t" => '\t', '"' => '\"', '\\' => '\\\\');
while (<IN>) {
	chomp;
	s/([\\\t"])/$s{$1}/ge;
	print OUT "\"$_\\n\"\n";
}
print OUT ";\n";
